- hosts: localhost
  vars_prompt:
          - name: "db_name"
            prompt: "enter database name"
            private: no
          - name: "user"
            prompt: "enter the master username"
            private: no 
          - name: "pass_wd"
            prompt: "enter the password for your database master"
            private: yes
  vars_files:
          - "secret.yml"
  tasks:
          - name: "provisioning the instances "
            ec2:
                    zone: "ap-south-1a"
                    assign_public_ip: "yes"
                    ec2_access_key: "{{ u }}"
                    ec2_secret_key: "{{ p }}"
                    count: 1
                    image: "ami-029e4db491be76287"
                    instance_tags:
                            Name: "mainos"
                    instance_type: "t3.micro"
                    key_name: "hadoop_slave_key"
                    region: "ap-south-1"
                    state: "present"
                    wait: yes
                    vpc_subnet_id: default
            register: X
          - name: "debugging the output"
            debug:
                    var: X['instances'][0]['public_ip']
          - meta: refresh_inventory
          - pause:
                  seconds: 30
- hosts: "tag_Name_mainos"
  tasks:
          - name: "installing httpd"
            package:
                    name: "httpd"
                    state: present
          - name: "installing prerequisites for wordpress"
            yum:
                    name:
                            - php
                            - tar
                            - mysql
          - name: "downloading the wordpress tar file"
            ansible.builtin.unarchive:
                    remote_src: yes
                    src: "https://wordpress.org/latest.tar.gz"
                    dest: "/var/www/html/"
          - shell: "amazon-linux-extras install php7.3 -y"
          - shell: "chown -R apache:apache /var/www/html/wordpress"
          - name: "starting the services of the httpd"
            service:
                    name: "httpd"
                    state: started
                    enabled: yes 
                    
                     
                    
